### ISSUE TITLE
Instruction to integrate Pika into Anim-Director agent

### ISSUE THREAD

**Issue by saifulbabo67646** [HITsz-TMG/Anim-Director#1]
It will be really helpful to get the instructions or guidelines to set up Pika with the Anim-director agent.

**Comment by HaoyuanShi** [comment]
If you have concerns about the Pika API, you might refer to unofficial resources, such as [Pika.art](https://www.pikapikapika.io/). If you have more detailed questions, please feel free to reach out to us.
