### ISSUE TITLE
interesting work! how  to eval Metrics? Could you offer your code ?

### ISSUE THREAD

**Issue by pzwstudy** [HITsz-TMG/Anim-Director#3]
![image](https://github.com/user-attachments/assets/2272dae5-8501-429a-9a82-868d4a2adf88)

![image](https://github.com/user-attachments/assets/bd5c349e-afff-472d-9c8b-566a21a1c1b9)

**Comment by HaoyuanShi** [comment]
Thanks for your interest!
For Image-Image Similarity and Text-Image Similarity, please check out [TaleCrafter](https://github.com/AILab-CVC/TaleCrafter);
For Distortion detection(i.e. Imaging Quality), Subject consistency, and Background consistency, you can refer to [VBench](https://github.com/Vchitect/VBench).

**Comment by pzwstudy** [comment]
thanks

**Comment by pzwstudy** [comment]
![image](https://github.com/user-attachments/assets/2641a1c4-d697-459b-a2af-4dbc44fb82c7)
how to use the imgur_client server , I registered the api from this website [https://apidocs.imgur.com/](url)  ,but failed ,Can you give me a way to apply for the imgur_client API  
Thanks！

**Comment by HaoyuanShi** [comment]
You can just refer to https://github.com/Imgur/imgurpython

**Comment by pzwstudy** [comment]
I see it!
The user manual of this official website is too old, and some of the guidance websites have been removed, and I don't know how to register the API
![image](https://github.com/user-attachments/assets/545a10d9-3c3b-453a-ace6-90c5c45b9a84)

**Comment by HaoyuanShi** [comment]
**https://api.imgur.com/oauth2/addclient** for client id and client_secret
**https://api.imgur.com/oauth2/authorize?client_id={your_client_id}&response_type=pin** for pin
**client.set_user_auth(credentials['access_token'],credentials['refresh_token'])** for access_token and refresh_token

**Comment by pzwstudy** [comment]
thanks! 
how to use pika to generate videos like this picture!
![image](https://github.com/user-attachments/assets/dcf168b7-8e56-41fc-a9cb-19e67f23768e)

**Comment by HaoyuanShi** [comment]
[Pika.art](https://www.pikapikapika.io/) for Pika api
As for concrete Pika parameter settings, due to the update of Pika version, you may try different combinations yourself.
